name: Mirror request / 镜像请求
description: Suggest setting up new mirrors / 建议设立新的镜像
title: "[镜像请求] "
labels:
- new-mirror

assignees:
- arnie97

body:
- type: markdown
  id: head
  attributes:
    value: |
      欢迎向 mirrors.tk 请求新镜像，请尽可能回答表单中的问题。

- type: checkboxes
  id: prerequisites
  attributes:
    label: 先决条件
    options:
    - label: |
        我已搜索确认，这个镜像未在[其他 issues](https://github.com/mirrors-tk/feedback/issues) 中请求过。
      required: true
    - label: |
        我确认上游的版权许可证允许二次分发（Redistribution）。

- type: textarea
  id: license
  attributes:
    label: 版权许可证
    placeholder: |
      请填写上游项目的版权许可证（LICENSE）类型。
      如果项目涉及到多种不同许可证，或使用了非常规的自拟许可证，请附上版权许可的 URL。
  validations:
    required: true

- type: textarea
  id: intro
  attributes:
    label: 项目主页与简介
    placeholder: |
      请简要阐述该软件的用途，主页地址，项目建立时间，上次更新时间等，
      以便说明建立其镜像的必要性。
  validations:
    required: true

- type: textarea
  id: peers
  attributes:
    label: 其他镜像站收录情况
    description: |
      [可参考此表查询中国大陆境内的主要镜像源](https://gitee.com/gsls200808/chinese-opensource-mirror-site/blob/master/README.md)，亦可在软件官网上查找全球镜像情况。
    placeholder: |
      请概述境内外镜像站对该软件项目的收录情况，亦可附上在其他镜像站请求镜像时的讨论链接。
      本站优先收录中国大陆无镜像源可用的软件项目，对于大陆其他镜像站已录的项目可能只做重定向而不复制。
  validations:
    required: true

- type: textarea
  id: upstream
  attributes:
    label: 上游地址与镜像方法
    description: |
      本站支持 rsync, http, ftp, sftp, git, s3 等通用协议和 apt, yum, pacman, GitHub Release 等特定结构仓库的同步。
    placeholder: |
      请给出所要同步内容本身的地址，而不是项目主页。
      请留意项目中是否有多个需要同步的仓库（例如软件包和 ISO 安装镜像分开存储）。
      如果上游或社区提供了针对该项目的专用同步工具，请予说明。
  validations:
    required: true

- type: textarea
  id: size
  attributes:
    label: 镜像大小与文件数量
    description: 若上游支持 rsync，可使用 `rsync --stats -anh rsync://example.org/example .` 命令进行统计。
    placeholder: |
      如果镜像内容由海量小文件构成，同步困难，本站将不予收录。
  validations:
    required: false

- type: textarea
  id: notes
  attributes:
    label: 备注
    placeholder: |
      以上问题之外的补充说明
  validations:
    required: false

- type: checkboxes
  id: todo-list
  attributes:
    label: 进度跟踪
    description: 本项供站长后续跟踪任务进度使用，无需关注和填写
    options:
      - label: |
          同意同步
          - [ ] 同步脚本
          - [ ] 存量同步成功
          - [ ] 增量同步成功
          - [ ] 可用性测试
          - [ ] 帮助文档

- type: markdown
  id: submit-help
  attributes:
    value: |
      ## 致谢
      感谢您提出宝贵的建议。如果无法提交表单，请返回页面上方，检查带红色 * 的必填项目是否有遗漏。
