name: Feature request / 功能提议
description: Suggest feature improvements / 提出功能改进意见
title: "[功能提议] "
labels:
- enhancement

assignees:
- arnie97

body:
- type: markdown
  id: head
  attributes:
    value: |
      欢迎向 mirrors.tk 提议新功能，请按以下模板填写。

- type: checkboxes
  id: prerequisites
  attributes:
    label: 先决条件
    options:
    - label: |
        我已搜索确认，这个镜像未在[其他 issues](https://github.com/mirrors-tk/feedback/issues?q=is%3Aissue) 中请求过。
      required: true

- type: textarea
  id: details
  attributes:
    label: 需求说明
  validations:
    required: true
